apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-reverse
  name: hello-world-reverse
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-reverse
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
