apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-reverse
  name: hello-world-reverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-reverse
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world-reverse
    spec:
      containers:
      - image: roshans416/python-hello-world-reverse:latest
        name: hello-world-reverse
        env:
        - name: HELLO-WORLD-SVC
          value: "hello-world"
        - name: PORT
          value: "8080"
        args: ["$(HELLO-WORLD-SVC)", "$(PORT)"]
        resources: {}
